import type { YnotCampaign } from "./types";

export const statusFilters = ["All", "New", "PSA10"] as const;

export type MockFeaturePack = {
  id: string;
  title: string;
  series: YnotCampaign["series"];
  costCoins: number;
  remainingLabel: string;
  heroLabel: string;
  tags: string[];
};

export const featuredCampaigns: YnotCampaign[] = [
  {
    id: "storefront-pokemon-gold-07",
    slug: "pokemon-gold-07",
    status: "live",
    titleTh: "Pokemon Gold #07",
    titleEn: "Pokemon Gold #07",
    series: "pokemon",
    priceThb: 150,
    costCoins: 150,
    mode: "instant_gacha",
    visibility: "public",
    totalSlots: 100,
    sortOrder: 10,
    startsAt: "2026-05-08T08:00:00.000Z",
    endsAt: null,
    createdAt: "2026-05-08T08:00:00.000Z",
    remainingSlots: 42,
    categoryLabel: "Pokemon",
    heroLabel: "Charizard SAR / Pikachu promo / Lucario VSTAR",
    displayTags: ["PSA10", "New Exclusive"],
    demo: true,
  },
  {
    id: "storefront-onepiece-treasure-03",
    slug: "one-piece-treasure-03",
    status: "live",
    titleTh: "One Piece Treasure #03",
    titleEn: "One Piece Treasure #03",
    series: "one_piece",
    priceThb: 120,
    costCoins: 120,
    mode: "instant_gacha",
    visibility: "public",
    totalSlots: 200,
    sortOrder: 20,
    startsAt: "2026-05-07T08:00:00.000Z",
    endsAt: null,
    createdAt: "2026-05-07T08:00:00.000Z",
    remainingSlots: 87,
    categoryLabel: "One Piece",
    heroLabel: "Manga rare / Leader parallel / sealed pack",
    displayTags: ["Manga", "New Exclusive"],
    demo: true,
  },
  {
    id: "storefront-pokemon-psa10",
    slug: "pokemon-psa10-exchange",
    status: "live",
    titleTh: "Pokemon PSA10 Exchange",
    titleEn: "Pokemon PSA10 Exchange",
    series: "pokemon",
    priceThb: 100,
    costCoins: 100,
    mode: "instant_gacha",
    visibility: "public",
    totalSlots: 200,
    sortOrder: 30,
    startsAt: "2026-05-06T08:00:00.000Z",
    endsAt: null,
    createdAt: "2026-05-06T08:00:00.000Z",
    remainingSlots: 87,
    categoryLabel: "Pokemon",
    heroLabel: "Pikachu / Rayquaza / Nanjamo",
    displayTags: ["PSA10"],
    demo: true,
  },
  {
    id: "storefront-onepiece-leader",
    slug: "one-piece-leader-parallel",
    status: "live",
    titleTh: "One Piece Leader Parallel",
    titleEn: "One Piece Leader Parallel",
    series: "one_piece",
    priceThb: 100,
    costCoins: 110,
    mode: "instant_gacha",
    visibility: "public",
    totalSlots: 160,
    sortOrder: 40,
    startsAt: "2026-05-05T08:00:00.000Z",
    endsAt: null,
    createdAt: "2026-05-05T08:00:00.000Z",
    remainingSlots: 56,
    categoryLabel: "One Piece",
    heroLabel: "OP manga / parallel / treasure box",
    displayTags: ["Manga"],
    demo: true,
  },
];

export const mockFeaturePacks: MockFeaturePack[] = [
  {
    id: "mock-pokemon-black-label",
    title: "Pokemon Black Label Chase",
    series: "pokemon",
    costCoins: 250,
    remainingLabel: "Preview stock",
    heroLabel: "Moonbreon / Charizard / Pikachu trophy concept",
    tags: ["PSA10", "High hit"],
  },
  {
    id: "mock-onepiece-gear-five",
    title: "One Piece Gear 5 Vault",
    series: "one_piece",
    costCoins: 220,
    remainingLabel: "Preview stock",
    heroLabel: "Manga rare, signature leader, treasure box concept",
    tags: ["Manga", "New"],
  },
  {
    id: "mock-pokemon-terastal",
    title: "Terastal Festival Burst",
    series: "pokemon",
    costCoins: 180,
    remainingLabel: "Preview stock",
    heroLabel: "SAR chase, Eevee heroes, trainer support concept",
    tags: ["SAR", "Foil"],
  },
  {
    id: "mock-onepiece-pirate-king",
    title: "Pirate King Treasure Box",
    series: "one_piece",
    costCoins: 160,
    remainingLabel: "Preview stock",
    heroLabel: "OP parallel, sealed booster, coin-back concept",
    tags: ["OP", "Value"],
  },
];

export const rewardTiers = [
  {
    rank: "S",
    name: "Signature hits",
    remain: "1 / 1",
    note: "Charizard SAR",
    cards: ["UR"],
  },
  {
    rank: "A",
    name: "Premium hits",
    remain: "2 / 4",
    note: "SR support cards",
    cards: ["SSR", "SSR", "SSR"],
  },
  {
    rank: "B",
    name: "Chase cards",
    remain: "6 / 12",
    note: "SR / RR",
    cards: ["SR", "SR", "SR", "SR"],
  },
  {
    rank: "C",
    name: "Foil cards",
    remain: "24 / 40",
    note: "R foil",
    cards: ["R", "R", "R", "R", "R"],
  },
  {
    rank: "D",
    name: "Base rewards",
    remain: "9 / 43",
    note: "Can be exchanged for coins",
    cards: ["N", "N"],
  },
] as const;
