import type { YnotCampaign } from "./types";

export const homeCategories = [
  { key: "all", labelTh: "ทั้งหมด", labelEn: "All", note: "Live mystery packs" },
  { key: "pokemon", labelTh: "โปเกมอน", labelEn: "Pokemon", note: "PSA10 / SAR / promo" },
  { key: "one_piece", labelTh: "วันพีซ", labelEn: "One Piece", note: "Manga / leader / serial" },
  { key: "hobby", labelTh: "ฮ็อบบี้", labelEn: "Hobby", note: "Sealed boxes and collectibles" },
  { key: "popmart", labelTh: "POP MART", labelEn: "POPMART", note: "Blind box / art toy" },
  { key: "apparel", labelTh: "เสื้อ", labelEn: "Apparel", note: "Limited merch and drops" },
] as const;

export const exchangeCategories = [
  "Pokemon",
  "One Piece",
  "Hobby",
  "POPMART",
  "Yu-Gi-Oh!",
  "Weiss",
  "Magic: The Gathering",
  "Duel Masters",
  "Apparel",
  "Others",
  "Mileage",
] as const;

export const statusFilters = ["All", "New", "Few left", "PSA10", "Login Bonus", "Oripa Gift", "Mileage", "Last chance"] as const;

export const featuredCampaigns: YnotCampaign[] = [
  {
    id: "storefront-pokemon-gold-07",
    slug: "pokemon-gold-07",
    status: "live",
    titleTh: "Pokemon Gold #07",
    titleEn: "Pokemon Gold #07",
    series: "pokemon",
    priceThb: 150,
    costCoins: 150,
    mode: "instant_gacha",
    visibility: "public",
    totalSlots: 100,
    sortOrder: 10,
    startsAt: "2026-05-08T08:00:00.000Z",
    endsAt: null,
    createdAt: "2026-05-08T08:00:00.000Z",
    remainingSlots: 42,
    categoryLabel: "Pokemon",
    heroLabel: "Charizard SAR / Pikachu promo / Lucario VSTAR",
    displayTags: ["PSA10", "New Exclusive"],
    demo: true,
  },
  {
    id: "storefront-onepiece-treasure-03",
    slug: "one-piece-treasure-03",
    status: "live",
    titleTh: "One Piece Treasure #03",
    titleEn: "One Piece Treasure #03",
    series: "one_piece",
    priceThb: 120,
    costCoins: 120,
    mode: "instant_gacha",
    visibility: "public",
    totalSlots: 200,
    sortOrder: 20,
    startsAt: "2026-05-07T08:00:00.000Z",
    endsAt: null,
    createdAt: "2026-05-07T08:00:00.000Z",
    remainingSlots: 87,
    categoryLabel: "One Piece",
    heroLabel: "Manga rare / Leader parallel / sealed pack",
    displayTags: ["Manga", "New Exclusive"],
    demo: true,
  },
  {
    id: "storefront-pokemon-psa10",
    slug: "pokemon-psa10-exchange",
    status: "live",
    titleTh: "Pokemon PSA10 Exchange",
    titleEn: "Pokemon PSA10 Exchange",
    series: "pokemon",
    priceThb: 100,
    costCoins: 100,
    mode: "instant_gacha",
    visibility: "public",
    totalSlots: 200,
    sortOrder: 30,
    startsAt: "2026-05-06T08:00:00.000Z",
    endsAt: null,
    createdAt: "2026-05-06T08:00:00.000Z",
    remainingSlots: 87,
    categoryLabel: "Pokemon",
    heroLabel: "Pikachu / Rayquaza / Nanjamo",
    displayTags: ["PSA10"],
    demo: true,
  },
  {
    id: "storefront-onepiece-leader",
    slug: "one-piece-leader-parallel",
    status: "live",
    titleTh: "One Piece Leader Parallel",
    titleEn: "One Piece Leader Parallel",
    series: "one_piece",
    priceThb: 100,
    costCoins: 110,
    mode: "instant_gacha",
    visibility: "public",
    totalSlots: 160,
    sortOrder: 40,
    startsAt: "2026-05-05T08:00:00.000Z",
    endsAt: null,
    createdAt: "2026-05-05T08:00:00.000Z",
    remainingSlots: 56,
    categoryLabel: "One Piece",
    heroLabel: "OP manga / parallel / treasure box",
    displayTags: ["Manga"],
    demo: true,
  },
];

export const rewardTiers = [
  { rank: "S", name: "Signature hits", remain: "1 / 1", note: "Charizard SAR", cards: ["UR"] },
  { rank: "A", name: "Premium hits", remain: "2 / 4", note: "SR support cards", cards: ["SSR", "SSR", "SSR"] },
  { rank: "B", name: "Chase cards", remain: "6 / 12", note: "SR / RR", cards: ["SR", "SR", "SR", "SR"] },
  { rank: "C", name: "Foil cards", remain: "24 / 40", note: "R foil", cards: ["R", "R", "R", "R", "R"] },
  { rank: "D", name: "Base rewards", remain: "9 / 43", note: "Can be exchanged for coins", cards: ["N", "N"] },
] as const;

export const exchangeCatalog = [
  { name: "(PSA10) Lucia", coin: "263,000", tickets: 0, sold: true, category: "Pokemon" },
  { name: "(PSA10) Sightseer", coin: "161,000", tickets: 0, sold: true, category: "Pokemon" },
  { name: "(PSA10) Marnie", coin: "98,000", tickets: 0, sold: true, category: "Pokemon" },
  { name: "Umbreon GX", coin: "74,800", tickets: 0, sold: true, category: "Pokemon" },
  { name: "(PSA10) Nanjamo", coin: "74,000", tickets: 0, sold: true, category: "Pokemon" },
  { name: "(PSA10) Clefairy", coin: "41,000", tickets: 0, sold: true, category: "Pokemon" },
  { name: "Ditto Reverse", coin: "39,800", tickets: 3, sold: false, category: "Pokemon" },
  { name: "Rayquaza V", coin: "31,800", tickets: 5, sold: false, category: "Pokemon" },
  { name: "Ichigeki VMAX", coin: "23,800", tickets: 2, sold: false, category: "Pokemon" },
] as const;

export const sampleCollectionCards = [
  { name: "YGO Card RL", code: "YGO-PH-00", type: "RL", coin: "2,430.00", selected: true },
  { name: "Lucario VSTAR", code: "PK-s-p-305", type: "PROMO", coin: "3,270.00", selected: true },
  { name: "Quarter Century Box", code: "yugioh-QCAC", type: "BOX", coin: "69.00", selected: false },
  { name: "Over Rush Pack 4", code: "yugioh-ORP4", type: "BOX", coin: "60.00", selected: false },
] as const;
